### ISSUE TITLE
Purple magnifying glass is hard to see in home page search bar

### ISSUE THREAD

**Issue by ashenden** [mesosphere/dcos-docs-site#151]
Screenshot: https://cl.ly/1j0f1D3M281P

The purple magnifying glass icon in the large search bar on the home page is difficult to see against the selected background.  Consider alternative styling or other visual solutions to make it more visible.

The design shows a purple icon, but it also has positioned the background in such a way so that it avoids the background image interfering with the icon (https://cl.ly/1b070Y0n2r2l).

**Comment by HypeUFO** [comment]
@ashenden I don't have photoshop to do a proper crop, but I was able to crop the background using css and avoid conflict with the magnifying glass. Let me know if it works for you. Thanks

**Comment by ashenden** [comment]
Looks so much better.  Thanks @HypeUFO
