### ISSUE TITLE
Services landing page should use boilerplate layout header

### ISSUE THREAD

**Issue by ashenden** [mesosphere/dcos-docs-site#167]
Screenshot: https://cl.ly/3e0c452l002m

The Services page and the Support page should use the standard boilerplate header look as seen in the design here (https://cl.ly/19361X2g452C).

ANY PAGE that is created as stand-alone 1-off page should use this layout.

**Comment by stbof** [comment]
Looks better at 55px instead of 60px.

**Comment by VanessaPC** [comment]
I have seen the master version of the repo, and it seems like the title font-size is adjusted to 55px. If this change is on master, then this issue may be resolved already.
