### ISSUE TITLE
DC/OS Version 1.12.0 GUI>Service>Version  (new item, and literally no explanation)

### ISSUE THREAD

**Issue by jose-guzman-rb** [mesosphere/dcos-docs-site#1714]
In the new version of DC/OS (1.12), you have added a new item in the GUI>Service Section. This item is the version column. Literally you just put this:

VERSION The version for the service

And nothing more. I just saw these versions fields in package from universe repo, but I couldn't find how can I put the version of my apps in this field. Could you provide us more info regarding this new feature? Because is new, and literally just say this in all the documentation.

**Comment by ck4adventure** [comment]
Hi there, the issues page of the docs repo is no longer actively maintained as a support channel. Please see if you can't find what you need here, https://docs.mesosphere.com/1.12/deploying-services/, or for further help see the support section: https://support.mesosphere.com/s/
