### ISSUE TITLE
Master Routes on page navigation broken

### ISSUE THREAD

**Issue by millerjem** [mesosphere/dcos-docs-site#1845]
Under version 1.12, the [Master Routes](https://docs.mesosphere.com/1.12/api/master-routes/) on page navigation is broken. All the bookmarks are assigned to #undefined. Although, the generate API specification has the correct bookmark references such as [Master Routes Cosmos](https://docs.mesosphere.com/1.12/api/master-routes/#cosmos). The issue is affecting all version of the API as well.

**Comment by ck4adventure** [comment]
Created Jira and closing, DCOS-42819
