### ISSUE TITLE
Provide mechanism to specify which DC/OS version is "latest"

### ISSUE THREAD

**Issue by stbof** [mesosphere/dcos-docs-site#280]
We need to be able to have versions under development that are available to view but are not considered the latest stable version and are not accessible from the home page.

Please see this example of declaring a `/latest` version: https://github.com/dcos/dcos-website/blob/develop/README.md#versioning

**Comment by stbof** [comment]
Until this is fixed, the 1.11 folder is parked in the root instead of under /pages.

**Comment by blakeandrewwood** [comment]
Documentation added here https://github.com/mesosphere/dcos-docs-site/wiki/Content#setting-latest-dcos-docs-version

**Comment by pavisandhu** [comment]
This was fixed with a code change by @gauripowale.
