### ISSUE TITLE
Selecting a new version of a page should try to display the page for that version

### ISSUE THREAD

**Issue by stbof** [mesosphere/dcos-docs-site#284]
If I am on a page, say installing DC/OS,  and I select a new version I'm taken back to the *home page* for the new version. In the existing docs sites I would be taken to the installing DC/OS for that new version

**Comment by VanessaPC** [comment]
I think it's a fairly common pattern in documentation.

We would need a button for it. So we don't change the current functionality of the top-left dropdown, or the buttons to the other documentation. 

I added an image for futher explanation: 
![screen shot 2018-01-29 at 14 28 33](https://user-images.githubusercontent.com/4052063/35515356-d7c6f2e8-0500-11e8-80c7-23fc8b2cf21d.png)

**Comment by ashenden** [comment]
I don't want us to design a new way of switching versions.  Looking at Stephanie's original comment above, what she is suggesting is that when someone changes the version using the top-left dropdown, we should attempt to put them on the same page in the selected version, assuming that page exists -- if not drop them on the homepage for the selected version.
