### ISSUE TITLE
Search results that are EE or OSS only pages should be labeled as such

### ISSUE THREAD

**Issue by ashenden** [mesosphere/dcos-docs-site#298]
Screenshot: https://cl.ly/420W3I0N010O

The page in the search result shown in the screenshot above is an entirely EE only page.  I even set my search filter Enterprise.  Yet, the result gives me no visual indication that this page is EE.  We should do some sort of labeling here to communicate that this page is EE (same for OSS) pages.

**Comment by niartenyaw** [comment]
In Jirra
