### ISSUE TITLE
Search result text highlight is intense

### ISSUE THREAD

**Issue by ashenden** [mesosphere/dcos-docs-site#299]
The pink highlighting, especially in page titles, is really intense.  Instead, I’d like to see us go with something like this:
- Keep titles simple.  Use the default styling applied by whatever `h#` we select for these titles.  If any emphasis is to be added to keywords, bold, maybe slightly darker text, is acceptable.  Not sure it’s needed, but could be useful.
- If any keywords match within the excerpt or description, those could also be bold/darker.

Maybe something like this if anything: https://cl.ly/0E3o1x1h1y2V

**Comment by blakeandrewwood** [comment]
Resolved
