### ISSUE TITLE
Link text incorrectly interpreted as a badge

### ISSUE THREAD

**Issue by stbof** [mesosphere/dcos-docs-site#301]
If any of the badge strings is link text, it is incorrectly rendered as a badge instead of a link. For example:

`Multiple region configuration support is [Enterprise](/1.9/overview/feature-maturity/#experimental).`

![screen shot 2017-12-14 at 1 37 22 pm](https://user-images.githubusercontent.com/20482960/34015643-f44c5e54-e0d3-11e7-917a-bc29140c83da.png)

**Comment by stbof** [comment]
@blakeandrewwood  I can't review this until you merge it into develop.

**Comment by VanessaPC** [comment]
It seems like this ticket is mentioned as resolved in this other one: 
https://github.com/mesosphere/dcos-docs-site/pull/316 

Maybe this ticket is resolved already and not awaiting review.
