### ISSUE TITLE
Printing page only prints whats in the viewport

### ISSUE THREAD

**Issue by stbof** [mesosphere/dcos-docs-site#303]
On this page http://docs2-staging.mesosphere.com/1.10/overview/features/  if you press print it only prints part of the page. 

https://cl.ly/0a3D2b0r0j1p

**Comment by blakeandrewwood** [comment]
I'm seeing 9 pages available for print on the page in the screen shots. You mentioned in our meeting today that someone internally had reported this issue. Are you able to recreate this issue @stbof ?

**Comment by stbof** [comment]
I didn't investigate because I never ever print anything. I just routed here because I thought it was a build issue. If you can't reproduce I will close the JIRA that sponsored this issue.

**Comment by stbof** [comment]
Can't reproduce.
