### ISSUE TITLE
Update wiki Development page with GIT_BRANCH env var requirement

### ISSUE THREAD

**Issue by stbof** [mesosphere/dcos-docs-site#309]
~/Documents/dcos-docs-site$ npm run dev

> mesosphere-docs@0.0.1 dev /Users/stephaniebodoff/Documents/dcos-docs-site
> NODE_ENV=development DEBUG=metalsmith-timer,metalsmith-revision,metalsmith-algolia node index.js

/Users/stephaniebodoff/Documents/dcos-docs-site/index.js:43
  throw new Error('Env var GIT_BRANCH has not been set.');

**Comment by blakeandrewwood** [comment]
Resolved
