### ISSUE TITLE
In-Line code is wrapped in bad places

### ISSUE THREAD

**Issue by stbof** [mesosphere/dcos-docs-site#327]
The inline code terms are wrapped badly: dcos b
ackup

over the line which makes it difficult to read.  

<img width="1384" alt="screen shot 2017-12-15 at 12 49 39 pm" src="https://user-images.githubusercontent.com/20482960/34132998-5735a3dc-e407-11e7-9a25-2bf46c0e7cc9.png">

**Comment by niartenyaw** [comment]
Code no longer wraps, it is overflow
