### ISSUE TITLE
Redirect /service-docs/* to /services/*

### ISSUE THREAD

**Issue by ashenden** [mesosphere/dcos-docs-site#340]
We use to use the route prefix `/service-docs/` but switched to `/services/`.  All URLs are currently 404'ing.

**Comment by ashenden** [comment]
@gauripowale reassigned this one to you.

**Comment by gauripowale** [comment]
There was a [fix](https://github.com/mesosphere/dcos-docs-site/commit/4acbb32c3b6f2d3f348bced53b5b157e922f3e11#diff-1f4dbe2fcc3cde1123efca10f16dc697R637) that was committed in for this.

Need to validate that the redirect from /service-docs/* to /services/* works once the staging build is green.

**Comment by ashenden** [comment]
@gauripowale I checked against that change, and it didn't seem to work.  We need some kind of wildcard catch that puts any slug/suffix of `/service-docs/` onto `/services/`.

@karlkfi do you know how to accomplish this?

We need the same things for `/latest/`.  Currently, `/latest/` goes to `/1.10/` which is great, but anything after `/latest/` 404s.  For example: `/latest/overview/` should go to `/1.10/overview/` but it is not.

**Comment by ashenden** [comment]
About to promote a fix @karlkfi suggested in `#ettrics`. 🤞

**Comment by ashenden** [comment]
Resolved.  Pushed to `master`
