### ISSUE TITLE
wkhtmltopdf should be replaced with chrome --headless

### ISSUE THREAD

**Issue by aayvazyan** [mesosphere/dcos-docs-site#341]
wkhtmltopdf image used in the https://raw.githubusercontent.com/mesosphere/dcos-docs-site/staging/docker/Dockerfile.pdf is pretty old and insufficient and should be replaced with chrome --headless. Current builds are taking 4 hours and the pdf and the resulting pdf-s doesn't have so high quality as they should have. 

The `Dockerfile` https://hub.docker.com/r/openlabs/docker-wkhtmltopdf/~/dockerfile/ uses `RUN wget http://downloads.sourceforge.net/project/wkhtmltopdf/0.12.2.1/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb` outdated url, which will break the build.

**Comment by niartenyaw** [comment]
This is now in Jira
