### ISSUE TITLE
Replace Recursive Directory/files lookup with 'Find'

### ISSUE THREAD

**Issue by aayvazyan** [mesosphere/dcos-docs-site#355]
Please replace the recursive file lookup in below files,  with 'find'. 
https://github.com/mesosphere/dcos-docs-site/blob/staging/scripts/pdf-concat.sh#L14-L26
https://github.com/mesosphere/dcos-docs-site/blob/staging/scripts/pdf-concat.sh#L14-L26

**Comment by niartenyaw** [comment]
I have moved this to Jira so it is in our backlog. Thanks!
