### ISSUE TITLE
Image shortcode doesn't respect stated defaults and truncates ALT text

### ISSUE THREAD

**Issue by stbof** [mesosphere/dcos-docs-site#368]
According to the test page:

![screen shot 2017-12-29 at 4 00 24 pm](https://user-images.githubusercontent.com/20482960/34449811-849dfa92-ecb1-11e7-95cf-a3ff4ece8cba.png)

 inline is the default. Here is my image shortcode:

[image src="/1.10/img/dcos-architecture-distributed-process-management-concept.png" alt="Concept of distributed process management in DC/OS" /]

Here is the result:

![screen shot 2017-12-29 at 3 59 48 pm](https://user-images.githubusercontent.com/20482960/34449818-9f87c7a2-ecb1-11e7-840b-3cde8410490e.png)

which has  **undefined** displayed as the image **caption**.

Also when I inspect the element, I see that the ALT text is truncated to the first word:

![screen shot 2017-12-29 at 3 59 28 pm](https://user-images.githubusercontent.com/20482960/34449824-bced173e-ecb1-11e7-98df-0b015fe0a8ec.png)

Finally I'd appreciate suggestions for how to scale the images on this page. It's kind of ridiculous how big they are.

https://docs.mesosphere.com/1.10/overview/architecture/distributed-process-management/

**Comment by VanessaPC** [comment]
I believe the alt and caption issue is fixed. I haven't been able to reproduce, however, if it appears somewhere else, attach below.
