### ISSUE TITLE
Custom Auth0 Encoder URL incorrect

### ISSUE THREAD

**Issue by natbaker** [mesosphere/dcos-docs-site#369]
DC/OS Custom Auth0 config Encoder URL on https://docs.mesosphere.com/1.10/security/oss/configure-your-security/ points to non-existent github account.  Update to reflect correct address: https://zivost.github.io/dcos-oauth-config/

**Comment by stbof** [comment]
This is a duplicate of https://jira.mesosphere.com/browse/DCOS_OSS-1843

**Comment by adamtheturtle** [comment]
See https://github.com/mesosphere/dcos-docs-site/pull/370#issuecomment-358295184 for potentially closing this with no action.
