### ISSUE TITLE
Wide code blocks break layout on Firefox

### ISSUE THREAD

**Issue by dirkjonker** [mesosphere/dcos-docs-site#403]
With the new documentation layout, if there is a (very) wide code block, Firefox does not wrap it into a box with a scrollbar: [screenshot](https://screenshots.firefox.com/8cjpABvaWtnMchBZ/docs.mesosphere.com)

Scrolling to the right breaks the layout of the page: [screenshot](https://screenshots.firefox.com/wmxdSSkTclpgwOny/docs.mesosphere.com)

This happens in various versions of Firefox: 57, 58 beta, nightly

**Comment by niartenyaw** [comment]
Thanks for pointing this out. We have added it to our Jira so we can track it. Thanks!
