### ISSUE TITLE
Can not retrive all the apps running in Marathon, thru the use of API

### ISSUE THREAD

**Issue by RoAndrei** [mesosphere/dcos-docs-site#409]
I'm trying to fetch all the running apps in my cluster by calling
`marathon.mesos:8080/v2/apps (with no other filters)`

I only get one app as the response: **/marathon,** app, but I have other 3 custom apps, all running in my cluster

Running this command, retrieves the 3 running apps but no **marathon:**
`dcos marathon app list`

The only difference I see is the framework name:
![untitled](https://user-images.githubusercontent.com/11091604/34883024-00f02a06-f7c1-11e7-9db0-6696ffdf203a.png)

This prevents marathon-lb from discovering all the services in the cluster.

Any ideas?
Thanks

**Comment by niartenyaw** [comment]
Hi, sorry that this hasn't been addressed. For support with marathon, please see this support page: https://mesosphere.github.io/marathon/support.html. Thanks!
