### ISSUE TITLE
Enable text of version selector in navigation panel to be different from the corresponding directory name

### ISSUE THREAD

**Issue by pavisandhu** [mesosphere/dcos-docs-site#410]
Currently, the release numbers in the version selector at the top of the left navigation panel reflect the name of the corresponding directory under /pages, i.e., 1.10 and 1.11 directories show up as "Mesosphere DC/OS 1.10" and  "Mesosphere DC/OS 1.11" respectively. We need a way to specify the version number in the navigation panel independently from the directory name. 

This is necessary so we can publish docs for a beta release, say 1.11 Beta, and have the version picker show "Mesosphere DC/OS 1.11 Beta" (instead of "Mesosphere DC/OS 1.11"). Currently the only way to do that is to rename the "1.11" directory to "1.11 Beta", but this is problematic because: 1) we would need to change all URLs that contain 1.11 to say 1.11 Beta instead (to avoid breaking all the links) and 2) rename the folder name and all URLs back to 1.11 when we do the final release. 

This is related to issue: https://github.com/mesosphere/dcos-docs-site/issues/280.

**Comment by MatApple** [comment]
I think if you change `navigationTitle` in the page's `index.md` it'll do what you're looking for. https://github.com/mesosphere/dcos-docs-site/issues/176#issuecomment-348251985

**Comment by pavisandhu** [comment]
@MatApple - Thanks for pointing out this fix. I just tested and it works, so closing this issue
