### ISSUE TITLE
Formatting is broken on Fault Domain Awareness & Capacity Extension

### ISSUE THREAD

**Issue by yishan-lin** [mesosphere/dcos-docs-site#516]
https://docs.mesosphere.com/1.11/deploying-services/fault-domain-awareness/

Considering this is a new feature, this may be a high priority.

I'll take a look at it and see if I can resolve.

**Comment by niartenyaw** [comment]
Formatting seems to be fine on my end. Maybe another change fixed this. If this is still a problem let me know and I'll add it to Jira but I'm going to close it for now.
