### ISSUE TITLE
Firefox code overflow issue

### ISSUE THREAD

**Issue by ashenden** [mesosphere/dcos-docs-site#519]
Example page: https://docs.mesosphere.com/1.9/monitoring/debugging/task-exec/

In Firefox, the content of the page forces a horizontal scrollbar.  In Chrome everything behaves normally.  Here is a video: https://cl.ly/2d2c3O3V162q

**Comment by VanessaPC** [comment]
Could I know what version of Firefox is it?

**Comment by ashenden** [comment]
FF/OSX latest

**Comment by niartenyaw** [comment]
This is still an issue but it is being tracked in Jira now. Thanks!
