### ISSUE TITLE
Update build scripts so they don't require a specific Node version

### ISSUE THREAD

**Issue by pavisandhu** [mesosphere/dcos-docs-site#628]
Step 3 for running a local build requires the Node version to be 8.1.2 exactly - higher versions do not work. See: https://github.com/mesosphere/dcos-docs-site/wiki/Local-Build.

This restriction is annoying (and creates extra work), as most people have higher versions of Node installed. The build scripts should work with any version of Node higher than some recent value.

**Comment by niartenyaw** [comment]
In Jira.
