### ISSUE TITLE
Formatting issue with API reference section

### ISSUE THREAD

**Issue by pavisandhu** [mesosphere/dcos-docs-site#648]
There is a formatting issue with this page, at least in Firefox on Mac: https://docs.mesosphere.com/1.10/security/ent/iam-api/#api-reference. The API reference is aligned to the middle of the page and spaces really weird. 

See attached screenshot. 
![firefox_pic](https://user-images.githubusercontent.com/32348643/36991846-d334267e-205d-11e8-8b74-1e17f2a3ebab.png)

**Comment by niartenyaw** [comment]
In Jira.
