### ISSUE TITLE
PDF builds failing as PhantomJS is being archived

### ISSUE THREAD

**Issue by pavisandhu** [mesosphere/dcos-docs-site#650]
The doc site PDF builds are failing as they use PhantomJS, which is being EOL’d by its owner. 
- Here’s the relevant error message: Removing intermediate container a722cbf82832
Step 16/26 : ADD https://github.com/ariya/phantomjs/releases/download/2.1.3/phantomjs /usr/bin/phantomjs
Service ‘pdf’ failed to build: ADD failed: Got HTTP status code >= 400: 404 Not Found
- Here’s the EOL announcement: https://github.com/ariya/phantomjs/issues/15344

Can we replace PhantomJS by another tool, or get the code from the repo and use a local copy? We need to fix this urgently, as it’s a blocker for our release on Wed (Mar 7).

**Comment by aayvazyan** [comment]
@kevinmiller-conley updated the phantomjs URL so the docker build now passes. 
https://github.com/mesosphere/dcos-docs-site/commit/c930aae267862cca2462dda21e9179f982711673

**Comment by aayvazyan** [comment]
Committed prebuilt docker image `mesosphere/phantomjs:2.1.1` https://github.com/mesosphere/dcos-docs-site/commit/c257afcc4c6b38ebb076cac55ebf4f8f27f73a6c. And the pdf build on staging went through. Please test the pdf-s and merge pr `cherry-pick` to master.
