### ISSUE TITLE
Configure kubernetes kubectl client

### ISSUE THREAD

**Issue by mfpierre** [mesosphere/dcos-docs-site#722]
Hi,

From the documentation https://github.com/mesosphere/dcos-docs-site/blob/master/pages/services/kubernetes/1.0.0-1.9.3/connecting-clients/index.md it says to use the command `dcos kubernetes kubeconfig` which I guess configures a config context within `kubectl` but it seems `'kubernetes' is not a dcos command.`

How is it supposed to be configured?

**Comment by rsltrifork** [comment]
> dcos package install kubernetes --cli
I wasted a lot of time on this. The CLI tool should ideally download the appropriate commands for the attach cluster itself.

**Comment by niartenyaw** [comment]
Thanks for pointing this out. We have added it to our Jira so we can track it. Thanks!
