### ISSUE TITLE
fail to install in GCE

### ISSUE THREAD

**Issue by floreslorca** [mesosphere/dcos-docs-site#730]
Hi i get this error:

```
"ERROR: (gcloud.compute.instances.create) Invalid value for [--scopes]: Flag format --scopes [ACCOUNT=]SCOPE,[[ACCOUNT=]SCOPE, ...] is removed. Use --scopes [SCOPE,...] --service-account ACCOUNT instead."], "stdout":"", "stdout_lines": []
```
It also failed on these two tasks `reomve masters from known_hosts file` and `remove masters IP from known_host file` with `mkstemp: No such file or directory"`

when i run `ansible-playbook -i hosts install.yml`

**Comment by floreslorca** [comment]
found the solution. just follow the recommendation above and remove "default=" at `--scopes` in file `tasks/create_master_instances.yml` and add --service-account default`

**Comment by niartenyaw** [comment]
Thanks for pointing this out. We have added it to our Jira so we can track it. Thanks!
