### ISSUE TITLE
Add OpenSearch definition

### ISSUE THREAD

**Issue by gm** [mesosphere/dcos-docs-site#740]
I'd like to enable OpenSearch on docs.mesosphere.com in order to make it externally accessible to the next iteration of search.mesosphere.com: 
https://community.algolia.com/instantsearch.js/v2/guides/opensearch.html

Looks like it's simply a matter of including an xml with the search definition.

**Comment by jpe442** [comment]
Are we already using InstantSearch.js for search.mesosphere.com? The above instructions are for configuring OpenSearch for integration with a InstantSearch.js engine. Is this right?

**Comment by niartenyaw** [comment]
Added it to our Jira so we can track it.
