### ISSUE TITLE
Change default project and fields in JIRA template used for submitting feedback 

### ISSUE THREAD

**Issue by pavisandhu** [mesosphere/dcos-docs-site#778]
Clicking the Feedback icon on any page of the doc site brings up a JIRA template. Make these changes to the template:

1. Change the default project to DCOS_OSS, instead DCOS_SITE
2. The template currently has too many fields, which is confusing. It should just have a plain text box, so it's easy for customers to provide comments. Use this ticket as a template: TBD

**Comment by niartenyaw** [comment]
Included in Jira
